-- Michael Gahn DESIGN CI BUILDER
-- 001_identity_security_foundation.sql
--
-- Production-safe foundation for an empty MariaDB database.
-- IDs are generated by the backend as UUIDv7 values and stored as BINARY(16).
-- Secrets and one-time tokens are stored only as hashes. Reversible data is
-- encrypted in the backend before it reaches this schema.

CREATE TABLE IF NOT EXISTS schema_migrations (
  version VARCHAR(128) NOT NULL,
  checksum_sha256 CHAR(64) NOT NULL,
  executed_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (version)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS users (
  id BINARY(16) NOT NULL,
  email_lookup_hash BINARY(32) NOT NULL,
  email_ciphertext MEDIUMBLOB NOT NULL,
  email_key_version SMALLINT UNSIGNED NOT NULL DEFAULT 1,
  password_hash VARCHAR(255) NOT NULL,
  password_changed_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  email_verified_at DATETIME(6) NULL,
  status ENUM('pending', 'active', 'locked', 'deleted') NOT NULL DEFAULT 'pending',
  last_login_at DATETIME(6) NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  UNIQUE KEY users_email_lookup_hash_uq (email_lookup_hash),
  KEY users_status_created_at_idx (status, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS roles (
  id BINARY(16) NOT NULL,
  slug VARCHAR(64) NOT NULL,
  label VARCHAR(128) NOT NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  UNIQUE KEY roles_slug_uq (slug)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS user_roles (
  user_id BINARY(16) NOT NULL,
  role_id BINARY(16) NOT NULL,
  assigned_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (user_id, role_id),
  CONSTRAINT user_roles_user_fk FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
  CONSTRAINT user_roles_role_fk FOREIGN KEY (role_id) REFERENCES roles (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS auth_sessions (
  id BINARY(16) NOT NULL,
  user_id BINARY(16) NOT NULL,
  token_hash BINARY(32) NOT NULL,
  device_label_ciphertext VARBINARY(1024) NULL,
  ip_hash BINARY(32) NULL,
  user_agent_hash BINARY(32) NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  last_used_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  expires_at DATETIME(6) NOT NULL,
  revoked_at DATETIME(6) NULL,
  PRIMARY KEY (id),
  UNIQUE KEY auth_sessions_token_hash_uq (token_hash),
  KEY auth_sessions_user_active_idx (user_id, revoked_at, expires_at),
  CONSTRAINT auth_sessions_user_fk FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS auth_one_time_tokens (
  id BINARY(16) NOT NULL,
  user_id BINARY(16) NOT NULL,
  purpose ENUM('email_verify', 'password_reset') NOT NULL,
  token_hash BINARY(32) NOT NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  expires_at DATETIME(6) NOT NULL,
  consumed_at DATETIME(6) NULL,
  PRIMARY KEY (id),
  UNIQUE KEY auth_one_time_tokens_hash_uq (token_hash),
  KEY auth_one_time_tokens_user_purpose_idx (user_id, purpose, expires_at),
  CONSTRAINT auth_one_time_tokens_user_fk FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS two_factor_methods (
  id BINARY(16) NOT NULL,
  user_id BINARY(16) NOT NULL,
  method ENUM('totp', 'webauthn') NOT NULL,
  label_ciphertext VARBINARY(1024) NULL,
  secret_ciphertext VARBINARY(1024) NULL,
  secret_nonce BINARY(12) NULL,
  secret_auth_tag BINARY(16) NULL,
  key_version SMALLINT UNSIGNED NULL,
  credential_id_hash BINARY(32) NULL,
  public_key_cose MEDIUMBLOB NULL,
  sign_count BIGINT UNSIGNED NULL,
  enabled_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  last_used_at DATETIME(6) NULL,
  disabled_at DATETIME(6) NULL,
  PRIMARY KEY (id),
  UNIQUE KEY two_factor_methods_credential_id_hash_uq (credential_id_hash),
  KEY two_factor_methods_user_active_idx (user_id, disabled_at),
  CONSTRAINT two_factor_methods_user_fk FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS two_factor_recovery_codes (
  id BINARY(16) NOT NULL,
  user_id BINARY(16) NOT NULL,
  code_hash BINARY(32) NOT NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  used_at DATETIME(6) NULL,
  PRIMARY KEY (id),
  UNIQUE KEY two_factor_recovery_codes_hash_uq (code_hash),
  KEY two_factor_recovery_codes_user_unused_idx (user_id, used_at),
  CONSTRAINT two_factor_recovery_codes_user_fk FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS audit_events (
  id BINARY(16) NOT NULL,
  actor_user_id BINARY(16) NULL,
  event_type VARCHAR(128) NOT NULL,
  target_type VARCHAR(64) NULL,
  target_id BINARY(16) NULL,
  ip_hash BINARY(32) NULL,
  metadata_ciphertext MEDIUMBLOB NULL,
  metadata_key_version SMALLINT UNSIGNED NULL,
  occurred_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  KEY audit_events_actor_occurred_idx (actor_user_id, occurred_at),
  KEY audit_events_target_idx (target_type, target_id, occurred_at),
  CONSTRAINT audit_events_actor_fk FOREIGN KEY (actor_user_id) REFERENCES users (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Checksum: SHA-256 of this migration with the checksum value represented by
-- PENDING_CHECKSUM. A future migration runner verifies that canonical value.
-- Re-running this statement must not change migration history.
INSERT INTO schema_migrations (version, checksum_sha256)
VALUES ('001_identity_security_foundation', '87708dccb8dc947d924683a250850972ba6a26689183fd44cfe050ea4b4f708e')
ON DUPLICATE KEY UPDATE checksum_sha256 = checksum_sha256;
